let popLinks = [
    "youtu.be/JGwWNGJdvx8",
    "youtu.be/gNi_6U5Pm_o",
    "youtu.be/fKopy74weus",
    "youtu.be/nfWlot6h_JM",
    "youtu.be/TmKh7lAwnBI",
    "youtu.be/dT2owtxkU8k",
    "youtu.be/TmKh7lAwnBI",
    "youtu.be/NaFd8ucHLuo",
    "youtu.be/aJOTlE1K90k",
    "youtu.be/36tggrpRoTI",
    "youtu.be/YSP71kIr2IQ",
    "youtu.be/sLgz57tguKo",
    "youtu.be/9HDEHj2yzew",
    "youtu.be/ZmDBbnmKpqQ",
    "youtu.be/4NRXx6U8ABQ",
    "youtu.be/JQj0GwR8yL8",
    "youtu.be/BFTf9eOTVxk?t=26",
    "youtu.be/bo_efYhYU2A?t=5",
    "youtu.be/D9G1VOjN_84?t=16",
    "youtu.be/6FlnXDIbmXA",
    "youtu.be/TKkcsmvYTw4",
    "youtu.be/vMLk_T0PPbk?t=11",
    "youtu.be/yYcyacLRPNs?t=8",
    "youtu.be/tbneQDc2H3I?t=20",
    "youtu.be/AEB6ibtdPZc",
    "youtu.be/DyDfgMOUjCI?t=5",
    "youtu.be/RQUuqbzQVsY",
    "youtu.be/OpQFFLBMEPI",
    "youtu.be/yKNxeF4KMsY",
    "youtu.be/il9nqWw9W3Y",
    "youtu.be/09R8_2nJtjg",
    "youtu.be/6NXnxTNIWkc",
    "youtu.be/sPTn0QEhxds",
    "youtu.be/D7JorwX31CQ",
    "youtu.be/MARsW26KXQg",
    "youtu.be/3lw6MZBmY-U",
    "youtu.be/7OrLroFa0AI",
    "youtu.be/FA2w-PMKspo",
    "youtu.be/M4vnmgZLA8s",
    "youtu.be/pBkHHoOIIn8",
    "youtu.be/oXBDZFtMcbg",
    "youtu.be/OPf0YbXqDm0",
    "youtu.be/498zUzNGQxY",
    "youtu.be/ZSznpyG9CHY",
    "youtu.be/jzD_yyEcp0M",
    "youtu.be/TyHvyGVs42U",
    "youtu.be/_I_D_8Z4sJE",
    "youtu.be/ClU3fctbGls",
    "youtu.be/l5-gja10qkw",
    "youtu.be/nqnkBdExjws",
    "youtu.be/kHLHSlExFis",
    "youtu.be/dfnCAmr569k",
    "youtu.be/D0_GWTy9FEM",
    "youtu.be/XOwihbur34E",
    "youtu.be/cIriwVhRPVA",
    "youtu.be/5GHXEGz3PJg",
    "youtu.be/1DhA69K3fZ4",
    "youtu.be/F1B9Fk_SgI0",
    "youtu.be/dMK_npDG12Q",
    "youtu.be/Mgfe5tIwOj0",
    "youtu.be/HQliEKPg1Qk",
    "youtu.be/8MPbR6Cbwi4",
    "youtu.be/kkLk2XWMBf8",
    "youtu.be/0ir1qkPXPVM",
    "youtu.be/QYh6mYIJG2Y",
    "youtu.be/6Mgqbai3fKo",
    "youtu.be/SJOgTMP8cs4",
    "youtu.be/FM7MFYoylVs",
    "youtu.be/EgBJmlPo8Xw",
    "youtu.be/YykjpeuMNEk",
    "youtu.be/5L6xyaeiV58",
    "youtu.be/iWZmdoY1aTE",
    "youtu.be/_bPa-VG0AWo",
    "youtu.be/eJnQBXmZ7Ek",
    "youtu.be/ffxKSjUwKdU",
    "youtu.be/LVEwL-sZzmM",
    "youtu.be/HUHC9tYz8ik",
    "youtu.be/leopt__ATR0",
];
pop = function(){
    let randx = Math.random()*popLinks.length;
    randx = parseInt(randx,10);
    let popLink = 'http://'+ popLinks[randx];
    window.open(popLink);
};

let rapLinks =[
    "youtu.be/_JZom_gVfuw",
    "youtu.be/fPO76Jlnz6c",
    "youtu.be/h2zgB93KANE?t=3",
    "youtu.be/phaJXp_zMYM",
    "youtu.be/yoYZf-lBF_U",
    "youtu.be/FcxBoDC39SI=80",
    "youtu.be/2StcXjwrGHY",
    "youtu.be/ktc9hsSfUck",
    "youtu.be/7Xue-dOOLiY?t=50",
    "youtu.be/O3pyCGnZzYA",
    "youtu.be/GSoQDaXh144",
    "youtu.be/9aofoBrFNdg?t=47",
    "youtu.be/k6mdRv0ZdR8?t=27",
    "youtu.be/PBwAxmrE194?t=10",
    "youtu.be/d3vOeCkeCNA",
    "youtu.be/qmj1q67NDAk",
    "youtu.be/h4UqMyldS7Q?t=25",
    "youtu.be/aIXyKmElvv8?t=32",
    "youtu.be/EC5LzftfcjI?t=21",
    "youtu.be/7ADgCeYJMN4",
    "youtu.be/RijB8wnJCN0",
    "youtu.be/K9F5xcpjDMU?t=18",
    "youtu.be/0c58ppLPJcQ?t=17",
    "youtu.be/2TN-kDEKxF0",
    "youtu.be/TMZi25Pq3T8",
    "youtu.be/dXrsuQ1-Bsw",
    "youtu.be/sb-gh6hJr30?t=16",
    "youtu.be/IJtHdkyo0hc",
    "youtu.be/Rz1Xn1vzOM4?t=13",
    "youtu.be/me3CPl_i4C4",
    "youtu.be/ThlhSnRk21E?t=8",
    "youtu.be/JFQXtAE7SiU",
    "youtu.be/GM92f-BUoow?t=22",
    "youtu.be/tNp9fzmXyn8?t=54",
    "youtu.be/WpQjN7yQ_8c",
    "youtu.be/WWSLM2lFjvg",
    "youtu.be/MTl_y-Nq1yo",
    "youtu.be/sNPnbI1arSE",
    "youtu.be/VC4ORS5n9Hg?t=20",
    "youtu.be/_CL6n0FJZpk",
    "youtu.be/NGbn6eaZmCY",
    "youtu.be/3mqhwhSerAw",
    "youtu.be/f8cHxydDb7o",
    "youtu.be/Cgoqrgc_0cM",
    "youtu.be/Mb1ZvUDvLDY",
    "youtu.be/IPfwPaBYuvg",
    "youtu.be/PMbELEUfmIA",
    "youtu.be/1plPyJdXKIY",
    "youtu.be/3KL9mRus19o",
    "youtu.be/WHRnvjCkTsw",
];

rap = function(){
    let randxx = Math.random()*rapLinks.length;
    randxx = parseInt(randxx,10);
    let rapLink = 'http://'+ rapLinks[randxx];
    window.open(rapLink);
}

let rockLinks =[
"youtu.be/tAGnKpE4NCI?t=40",
"youtu.be/ErvgV4P6Fzc",
"youtu.be/kijpcUv-b8M",
"youtu.be/Lo2qQmj0_h4?t=3",
"youtu.be/etAIpkdhU9Q?t=1",
"youtu.be/TLV4_xaYynY?t=3",
"youtu.be/kXYiU_JCYtU",
"youtu.be/eVTXPUF4Oz4",
"youtu.be/7QU1nvuxaMA",
"youtu.be/v2AC41dglnM",
"youtu.be/ZhIsAZO5gl0",
"youtu.be/kXYiU_JCYtU",
"youtu.be/HFguWjXkpvM",
"youtu.be/hTWKbfoikeg",
"youtu.be/AMh7FPlEnSU",
"youtu.be/bpOSxM0rNPM",
"youtu.be/vx2u5uUu3DE",
"youtu.be/vx2u5uUu3DE",
"youtu.be/XFkzRNyygfk",
"youtu.be/lDK9QqIzhwk",
"youtu.be/xwtdhWltSIg",
"youtu.be/tAGnKpE4NCI",
"youtu.be/6Ejga4kJUts",
"youtu.be/OMOGaugKpzs",
"youtu.be/pAgnJDJN4VA",
"youtu.be/Soa3gO7tL-c",
"youtu.be/4N1iwQxiHrs?t=25",
"youtu.be/fV4DiAyExN0?t=22",
"youtu.be/u9Dg-g7t2l4",
"youtu.be/L3wKzyIN1yk",
"youtu.be/l482T0yNkeo",
"youtu.be/54LEywabkl4",
"youtu.be/lDK9QqIzhwk",
"youtu.be/rMbATaj7Il8",
"youtu.be/X9bOsdHckhg",
"youtu.be/diKz9udywg4",
"youtu.be/sfR_HWMzgyc",
"youtu.be/T2PAkPp0_bY",
"youtu.be/1cQh1ccqu8M",
"youtu.be/76RbWuFll0Y",
"youtu.be/Qq4j1LtCdww",
"youtu.be/2lg_k1SwrQ0"
];

rock = function(){
    let randxxx = Math.random()*rockLinks.length;
    randxxx = parseInt(randxxx,10);
    let rockLink = 'http://'+ rockLinks[randxxx];
    window.open(rockLink);
};

let metalLinks =[
"youtu.be/xnKhsTXoKCI",
"youtu.be/9d4ui9q7eDM",
"youtu.be/EzgGTTtR0kc",
"youtu.be/CD-E-LDc384",
"youtu.be/nM__lPTWThU",
"youtu.be/CSvFpBOe8eY",
"youtu.be/K6_zsJ8KPP0",
"youtu.be/K6_zsJ8KPP0",
"youtu.be/dKILvAggpYw",
"youtu.be/Wm58sGEdgAw",
"youtu.be/pAgnJDJN4VA",
"youtu.be/uebInqG1pJI",
"youtu.be/AkFqg5wAuFk",
"youtu.be/6fVE8kSM43I",
"youtu.be/HL9kaJZw8iw",
"youtu.be/9fM3ylFs3hs",
"youtu.be/rvuO2EvCTAE",
"youtu.be/iywaBOMvYLI",
"youtu.be/3YxaaGgTQYM",
"youtu.be/IZ7Aif5aXlQ",
"youtu.be/VyctTU_0FiM",
"youtu.be/9sTQ0QdkN3Q",
"youtu.be/Y2e47wBWTV8",
"youtu.be/6NvntVb0Q_o"
]

metal = function(){
    let randxxxx = Math.random()*metalLinks.length;
    randxxxx = parseInt(randxxxx,10);
    let metalLink = 'http://'+metalLinks[randxxxx];
    window.open(metalLink);
}